import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Enrollify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <nav>
          <Link className="p-4" href={'/'}>Home</Link>
          <Link href={'about'}>About</Link>
        </nav>
        {children}
        
        
    </body>
    </html>
  );
}
